services:
  db:
    image: postgres:15
    container_name: student_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: student_registration
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: student_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:root@db:5432/student_registration

  frontend:
    build: ./frontend
    container_name: student_frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata:
